create table auditoria_Usuario(
id_audi int auto_Increment,
Audi_UsNombreAnterior varchar(100),
Audi_UsTelefonoAnterior bigint,
Audi_UsEmailAnterior char(200),
Audi_TblSeccion_Noticias_SNCodigoAnterior int,
Audi_TblMapa_Puntos_Reciclaje_MPRCodigoAnterior int,
Audi_TblRanking_RanCodigoAnterior int,
Audi_TblRegistro_RegCodigoAnterior int,
Audi_TblSeccion_Guias_Aprendizaje_SGACodigoAnterior int,
Audi_UsNombreNuevo varchar(100),
Audi_UsTelefonoNuevo bigint,
Audi_UsEmailNuevo char(200),
Audi_TblSeccion_Noticias_SNCodigoNuevo int,
Audi_TblMapa_Puntos_Reciclaje_MPRCodigoNuevo int,
Audi_TblRanking_RanCodigoNuevo int,
Audi_TblRegistro_RegCodigoNuevo int,
Audi_TblSeccion_Guias_Aprendizaje_SGACodigoNuevo int,
Audi_LlavePrimaria int,
Audi_FecharModificacion datetime,
Audi_Usuario varchar(45),
Audi_Accion varchar(45),
primary key (id_audi))